### PR TITLE
added contributing, contributors, and edge detection docstring

### PR DESCRIPTION
**Pull request by trevorkwan**

### CODE REVIEW

**Review by brendoncampbell — APPROVED** [review]
Looking good - thanks Trevor!

**Review by brendoncampbell — COMMENTED** [review]
@trevorkwan I just noticed we've got different `contributing.md` instructions on each repo, since the python project one was auto-generated. Wondering if it might make sense to keep them consistent. What do you think?

**Comment by katieb1** [comment]
I agree with Brendon, I think maybe we should make the contributing files match between the two repos. Did you edit the pymagine one as well, Trevor? Or is it the default one created with cookiecutter?

**Comment by trevorkwan** [comment]
Pymagine is currently the default one created with cookiecutter and I was thinking we could use that as well for Rmagine

**Comment by brendoncampbell** [comment]
You're right - my mistake. I mistakenly mentioned we should update `pymagine` but its the reverse!

**Review by brendoncampbell — APPROVED** [review]
Awesome thanks for updating, I think we're all set to version

**Pull request merged**
